title: Jackson's Personal Site
description: A clean, minimal blog to showcase my content.
url: "https://username.github.io" # Change this to your URL
theme: jekyll-theme-clean-blog
markdown: kramdown

# Social media links
social:
  github: "https://github.com/username"
  twitter: "https://twitter.com/username"
