title: Jackson's Website
email: jcmiskill@gmail.com
description: a repository for my thoughts
remote_theme: pages-themes/cayman@v0.2.0
baseurl: "j-miskill.github.io"
url: ""
markdown: kramdown
github_username: j-miskill



plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
