title: Jackson's Website
email: jcmiskill@gmail.com
description: a repository for my thoughts
theme: hacker
baseurl: "j-miskill.github.io"
url: ""
markdown: kramdown
github_username: j-miskill



plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
