name: secrets and environment variables

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}

    # setting secret variables from GitHub secrets
    steps:
      - name: read working directory
        run: pwd
      - name: set the user id variable
        run: sed -i 's/YOUR_USER_ID/${{ secrets.USER_ID }}/g' /_includes/scripts.html

      - name: set the service id variable
        run: sed -i 's/YOUR_SERVICE_ID/${{ secrets.SERVICE_ID }}/g' /_includes/scripts.html

      - name: set the template id variable
        run: sed -i 's/YOUR_TEMPLATE_ID/${{ secrets.TEMPLATE_ID }}/g' /_includes/scripts.html
      
    
