name: secrets and environment variables

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    # setting secret variables from GitHub secrets
    steps:
      - uses: actions/checkout@v4
      - name: read working directory
        run: pwd
      - name: list secrets
        run: echo ${{ secrets.USER_ID }}
      - name: set the user id variable
        run: sed -i 's/YOUR_USER_ID/{{ secrets.USER_ID }}/g' _includes/scripts.html

      - name: set the service id variable
        run: sed -i 's/YOUR_SERVICE_ID/{{ secrets.SERVICE_ID }}/g' _includes/scripts.html

      - name: set the template id variable
        run: sed -i 's/YOUR_TEMPLATE_ID/{{ secrets.TEMPLATE_ID }}/g' _includes/scripts.html


